### ISSUE TITLE
What's in a name? That which we call a host / By any other name would smell as sweet

### ISSUE THREAD

**Issue by cb372** [higherkindness/mu-haskell#157]
If I have a server running on localhost, this works fine:

```haskell
main = do
  let config = grpcClientConfigSimple "127.0.0.1" 9123 False
  Right conn <- initGRpc config msgProtoBuf @WeatherService
  putStrLn "Connected"
```

but this:

```haskell
main = do
  let config = grpcClientConfigSimple "localhost" 9123 False
  Right conn <- initGRpc config msgProtoBuf @WeatherService
  putStrLn "Connected"
```

gives me an error:

```
client: Network.Socket.connect: <socket: 5>: does not exist (Connection refused)
```

Does the first argument to `grpcClientConfigSimple` have to be an IP address? That's not what the documentation suggests.

Maybe this problem only occurs on localhost and it's fine with external hostnames? I haven't checked.

**Comment by serras** [comment]
[This StackOverflow question](https://stackoverflow.com/questions/33874370/exception-connect-does-not-exist-connection-refused-when-trying-to-connect-t) seems to be related

**Comment by serras** [comment]
In fact, this seems to be a [known bug](https://mail.haskell.org/pipermail/haskell-cafe/2010-June/078602.html) in the implementation of `network`. If `localhost` resolves to more than one address (for example, an IPv6 one and a IPV4 one), it just tries the first one - which does not work in our case - instead of attempting all of them.

**Comment by cb372** [comment]
Thanks for investigating.
